# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vhd files/Nexys4DDR_Master.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]

# IP: ip/clk_wiz_12mhz/clk_wiz_12mhz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_12mhz || ORIG_REF_NAME==clk_wiz_12mhz}]
